services:
  app:
    build:
      context: .
      target: production
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - postgres

  postgres:
    image: "postgres"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

